variable region {}
variable project_name {}
variable vpc_cidr {}
variable pub_sub_1a_cidr {}
variable pub_sub_2b_cidr {}
variable priv_sub_3a_cidr {}
variable priv_sub_4b_cidr {}
variable db_username {}
variable db_password {}